ARG JDK_VERSION

FROM alvrme/alpine-android-base:jdk${JDK_VERSION}

ARG BUILD_TOOLS
ARG TARGET_SDK
ARG NDK_VERSION

# Install SDK Packages
# @todo We don't actually need NDK, right?
#RUN sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" --install "ndk;28.1.13356709"

# Since we don't get the Docker metadata, we need to write environment variables into /etc/profile
RUN echo "export PATH=\"$PATH\"" >> /etc/profile.d/99-godot.sh \
 && echo "export JAVA_HOME=\"$JAVA_HOME\"" >> /etc/profile.d/99-godot.sh \
 && echo "export ANDROID_SDK_ROOT=\"$ANDROID_SDK_ROOT\"" >> /etc/profile.d/99-godot.sh \
 && echo "export ANDROID_HOME=\"$ANDROID_HOME\"" >> /etc/profile.d/99-godot.sh

# @todo Do the aapt hack thing?
